下記エラーが出たのでvue-tscを追加
ERROR  Cannot find module 'vue-tsc/package.json'                                                              3:20:17 PM
Require stack:
- /Users/michi/hobby/menu_app/admin_frontend/node_modules/vite-plugin-checker/dist/checkers/vueTsc/prepareVueTsc.js

    at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
    at Function.resolve (node:internal/modules/helpers:193:19)
    at node_modules/vite-plugin-checker/dist/checkers/vueTsc/prepareVueTsc.js:8:36
    at ModuleJob.run (node:internal/modules/esm/module_job:325:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24)
    at async createCheckers (node_modules/vite-plugin-checker/dist/main.js:31:37)
    at async BasicMinimalPluginContext.config (node_modules/vite-plugin-checker/dist/main.js:65:18)
    at async runConfigHook (node_modules/vite/dist/node/chunks/config.js:35934:15)
    at async resolveConfig (node_modules/vite/dist/node/chunks/config.js:35436:13)
    at async _createServer (node_modules/vite/dist/node/chunks/config.js:25361:67)
    at async buildClient (node_modules/@nuxt/vite-builder/dist/index.mjs:1188:24)
    at async withLogs (node_modules/@nuxt/vite-builder/dist/index.mjs:2292:3)
    at async handleSerialBuilds (node_modules/@nuxt/vite-builder/dist/index.mjs:2284:3)
    at async bundle (node_modules/@nuxt/vite-builder/dist/index.mjs:2251:5)
    at async bundle (node_modules/nuxt/dist/index.mjs:6929:5)
    at async build (node_modules/nuxt/dist/index.mjs:6789:3)
    at async Promise.all (index 1)
    at async #initializeNuxt (node_modules/@nuxt/cli/dist/dev-CGEtJnLN.mjs:520:3)
    at async NuxtDevServer.init (node_modules/@nuxt/cli/dist/dev-CGEtJnLN.mjs:383:3)
    at async initialize (node_modules/@nuxt/cli/dist/dev-CGEtJnLN.mjs:684:2)
    at async Object.run (node_modules/@nuxt/cli/dist/dev-DzDtIj6D.mjs:206:51)
    at async runCommand (node_modules/citty/dist/index.mjs:316:16)
    at async runCommand (node_modules/citty/dist/index.mjs:307:11)
    at async runMain (node_modules/citty/dist/index.mjs:445:7)